### ISSUE TITLE
为什么我npm i不了？？

### ISSUE THREAD

**Issue by seilamiuluce** [sl1673495/vue-netease-music#1]
aging/better-scroll-c7c78135/.eslintignore'
npm WARN tar ENOENT: no such file or directory, open '/Users/zhangxi/vue-netease-music/node_modules/.staging/better-scroll-c7c78135/.travis.yml'
npm WARN tar ENOENT: no such file or directory, open '/Users/zhangxi/vue-netease-music/node_modules/.staging/better-scroll-c7c78135/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/Users/zhangxi/vue-netease-music/node_modules/.staging/better-scroll-c7c78135/README_zh-CN.md'
npm ERR! Unexpected end of JSON input while parsing near '...":"sha512-AHCPCJdPe/h'
npm WARN tar ENOENT: no such file or directory, open '/Users/zhangxi/vue-netease-music/node_modules/.staging/element-ui-95891b15/CHANGELOG.fr-FR.md'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhangxi/.npm/_logs/2019-08-05T07_49_11_257Z-debug.log

**Comment by liuzihua699** [comment]
npm install

**Comment by sl1673495** [comment]
删除依赖 再重装一下试试
