### ISSUE TITLE
async created () {} 写法的问题

### ISSUE THREAD

**Issue by cosmosdawn** [sl1673495/vue-netease-music#10]
发现组件中使用了大量的async created () {}的写法，这种写法应该是不被vue所支持的。

参考： https://github.com/vuejs/vue/issues/7333

https://github.com/vuejs/vue/issues/7209

**Comment by sl1673495** [comment]
想一下他说的不支持和我的用法之间的区别

**Comment by luozejian** [comment]
这么写应该了 为了在生命周期钩子函数写 await IDE 不提示错误?
