### ISSUE TITLE
您好 vue新手 ，想要将baseurl换成自己的api地址（http），但是network中看到的是https,导致访问不到，是需要在某个地方配置什么吗？

### ISSUE THREAD

**Issue by wudan1874** [sl1673495/vue-netease-music#18]
您好 vue新手 ，想要将axios.creat的 baseurl换成自己的api地址（http），但是network中看到的是https,导致访问不到，是需要在某个地方配置什么吗？

**Comment by wudan1874** [comment]
![image](https://user-images.githubusercontent.com/34229272/76635031-c778f100-6581-11ea-812b-22773e48145c.png)

**Comment by wsm14** [comment]
解决了吗，想问下怎么解决的
