### ISSUE TITLE
想问下删除的请求没有吗？

### ISSUE THREAD

**Issue by act2009** [sl1673495/vue-netease-music#26]
vue新手，下载下来学习的，在src/api/comment.js想新建一个request.delete()请求发现后端api接受不到（自己本地的api测试）

//删除评论
export const delComment = ids=> request.delete(`/v1/comment/del`,{ ids })

用request.get()/request.post()都可以接收到参数 ，想问问删除的请求怎么写？

**Comment by sl1673495** [comment]
删除的话估计要种cookie，鉴权了。现在这套登录做不到。
