### ISSUE TITLE
能分享下icon的项目吗？

### ISSUE THREAD

**Issue by fakaka** [sl1673495/vue-netease-music#29]
要加些图标复用

**Comment by SoldierMr** [comment]
他这个是在public文件夹中的index.html，link标签中有引用到的，部署到线上去的

**Comment by fakaka** [comment]
> 他这个是在public文件夹中的index.html，link标签中有引用到的，部署到线上去的

是啊，但我要添加或者替换图标就得增加个iconfont项目了啊，所以想要他的项目拷贝修改
