### ISSUE TITLE
前端页面数据未显示，不会运行后端

### ISSUE THREAD

**Issue by wangjianliqq** [sl1673495/vue-netease-music#3]
你好，首先我npm install  npm run serve之后，默认到http://localhost:8080
但是页面没有显示数据；接着你在readme里面写的 “后端项目 地址 clone下来之后执行node app.js，默认启动在3000端口，之后就可以访问到接口了”这个怎么运行，请帮忙详细说明，谢谢了
![Snip20190812_1](https://user-images.githubusercontent.com/31639100/62876620-ee571680-bd57-11e9-9cff-4762ae75565e.png)

**Comment by sl1673495** [comment]
clone下来那个后端项目后 进入那个项目的文件夹 然后在命令行执行node app.js就启动后端服务了
