### ISSUE TITLE
banner & loading background

### ISSUE THREAD

**Issue by cnbailian** [sl1673495/vue-netease-music#4]
客户端 banner 图片是圆角的，看起来更舒服

歌单切换时，loading 最好加个 background，类似左上角四个菜单的切换效果就好
现在切换歌单时，歌单图片和歌曲图片是分别替换的，有很明显的时间差，很别扭

**Comment by sl1673495** [comment]
banner的圆角已经加上
歌单的问题是因为本质上歌单之间是相同的路由，所以只是替换了数据而不是真正的跳转新的路由。
