### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by simplove** [sl1673495/vue-netease-music#42]
演示站点也挂了

**Comment by zhouguangyou1994** [comment]
因为用的是别人的api,网站证书过期了，导致加载不了，这个证书过期了 https://api.mtnhao.com/top/song?type=0 ，怎么样用自己的API呢？

**Comment by zhouguangyou1994** [comment]
找到js/app.xxx.js  搜索 https://api.mtnhao.com/ 然后替换成自己的API就不用受制于人了。
