### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Clearlee** [sl1673495/vue-netease-music#5]
$ npm run serve

> vue-netease-muisc@3.2.15 serve E:\work\H5\project\vue-netease-music-master
> vue-cli-service serve

 INFO  Starting development server...
 98% after emitting CopyPlugin ERROR  Failed to compile with 2 errors17:41:19

These relative modules were not found:

* ./modules/music in ./src/store/index.js
* ./modules/user in ./src/store/index.js

**Comment by sl1673495** [comment]
重新拉一下代码再跑
