### ISSUE TITLE
一些细节优化

### ISSUE THREAD

**Issue by flightmakers** [sl1673495/vue-netease-music#57]
作为一个专业的魔改工程师  
看到你的项目竟然没有打算魔改  
不过,(Blitz就不说了还没上线QwQ)  
1. 
![image](https://user-images.githubusercontent.com/74816052/129433513-5ee8bfec-6571-4962-a138-c7cb19306f36.png)
建议使用CSS禁用select
2.
![image](https://user-images.githubusercontent.com/74816052/129433524-7e8ef273-378c-4894-a61d-c06f2cd16df0.png)
建议把自个Github键扔了
3.
![image](https://user-images.githubusercontent.com/74816052/129433538-153e14dc-6105-489e-9a0b-42a1c9723eca.png)
这个展开键和原版有差异
4.
![image](https://user-images.githubusercontent.com/74816052/129433545-5d0b6640-d27c-4c83-a7f3-8a6d321b5efb.png)
总体感觉还是不错的

**Comment by teadrinker2015** [comment]
1.不建议默认禁用select，官方也几乎没有禁用select（除了用户名、评论时间等）。这方面的自由度是此类第三方app应该提供的
2.github键最好留着，方便进来点star、或提issue
3.同意，播放栏的封面小图标始终模糊确实不太好。建议做成hover的动作

**Comment by flightmakers** [comment]
就是我的这个触控板总是wtf一样的选中一些东西
参考apple.com.cn, 如果你按住ctrla, tab栏上的几个a标签是user-selectnone的
而miui.com的学习成果就不咋地(毕竟就是19px团队的作品)
