### ISSUE TITLE
[Question] 是使用什么架构搭建桌面应用的？

### ISSUE THREAD

**Issue by yujqiao** [sl1673495/vue-netease-music#6]
对本项目比较好奇，看了下 package.json 并没有找到 electron 。那是怎么做到的呢？

**Comment by wangqiaoqiaogithub** [comment]
没有elecron版本的PC端应用，看README.md简介里面作者大大只是想做一个**pc 端 web 版**的网易云音乐

**Comment by wangqiaoqiaogithub** [comment]
没有electron版本的PC端应用，看README.md简介里面作者大大只是想做一个pc 端 web 版的网易云音乐 @Rapiz1

**Comment by wangqiaoqiaogithub** [comment]
没有electron版的PC端应用，看README.md简介里面作者大大只是想做一个**Pc端 web** 版的网易云音乐,希望对你有帮助 @Rapiz1

**Comment by yujqiao** [comment]
这样啊 谢谢
