### ISSUE TITLE
项目无法打包

### ISSUE THREAD

**Issue by hash070** [sl1673495/vue-netease-music#63]
执行[npm i]命令后报错，三台服务器都无法成功运行这条命令
阿里云(CentOS7)
![image](https://user-images.githubusercontent.com/62081013/151653210-be3b2205-0b3c-441b-af79-2a8a8dad6b38.png)
tx云(CentOS7)
![image](https://user-images.githubusercontent.com/62081013/151653220-3621346f-9eec-4022-9f61-6662fc3bfe40.png)
另一台(CentOS8)
![image](https://user-images.githubusercontent.com/62081013/151653243-340b2123-39cb-4890-aa5e-46eed9fa60ee.png)

**Comment by hash070** [comment]
附阿里云服务器上的报错log
[https://dr.hash070.top/s/xMib](url)

**Comment by Chookyin** [comment]
+1

**Comment by Chookyin** [comment]
+1报错一模一样

**Comment by sl1673495** [comment]
修复了，node-sass 换成 dart-sass 就好了
